theme: jekyll-theme-minimal
title: Memória da Física Brasileira
description: Resgatando a história da física no Brazil
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
