theme: jekyll-theme-minimal
title: Memória da Física Brasileira
description: Resgatando a história da física no Brasil
show_downloads: False
navigation:
  - title: Página principal
    url: /
  - title: Biografias
    url: biblio/biblio_index
